api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('', views.LaporanView.as_view(), name='LaporanView'),
    path('create/', views.LaporanCreateView.as_view(), name='LaporanView'),   
]

laporan/urls.py
from django.urls import path, include
from laporan import views

app_name = 'laporan'

urlpatterns = [
    path('lihatLaporan/', views.lihatLaporan, name='lihatLaporan'),
    path('ubahLaporan/', views.ubahLaporan, name='ubahLaporan'),
    path('ubahLaporan/<int:id>', views.ubahStatusLaporan, name='ubahStatusLaporan'),
    path('lihatUbahLaporan/', views.lihatUbahLaporan, name='lihatUbahLaporan'),
    path('getData/', views.getData, name='getData'),
    path('getDataFull/', views.getDataFull, name='getDataFull'),
    path('getData/<str:nama>', views.getDataNama, name='getDataNama'),
]

tk1/urls.py
from django.contrib import admin
from django.urls import path, include
# from rest_framework import DefaultRouter
from api.views import LaporanView

# router = DefaultRouter()


urlpatterns = [
    path('admin/', admin.site.urls),
    path('buatLaporan/', include('formLaporan.urls')),
    path('laporan/', include('laporan.urls')),
    path('tentang-kami/', include('about.urls')),
    path('', include("landingPage.urls")),
    path('api/', include("api.urls"))
]

laporan/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date

STATUS = [('Diproses', 'Diproses'),
          ('Ditolak', 'Ditolak'),
          ('Selesai', 'Selesai')]

class PilihStatus(models.Model):
    status = models.CharField(max_length=50, choices=STATUS, default="---")

    #Agar memunculkan "value" dari statusnya
    def __str__(self):
        return self.status

laporan/forms.py
from django import forms
from formLaporan.models import Laporan
from django.forms import ModelForm

class FormPilihStatus(ModelForm):
    class Meta:
        model = Laporan
        fields = ['status']
        labels = {'status' : ''}
        widgets = {'status' : forms.Select(
            attrs={
                'class' : 'form-control',
                'placeholder' : "jeje"
                }
            )}

laporan/views.py
from django.shortcuts import render, redirect
from django.core import serializers
from django.http import HttpResponse

from formLaporan.models import Laporan
from formLaporan.forms import BuatLaporan
from .forms import FormPilihStatus
# Create your views here.

def lihatLaporan(request):
    respon = Laporan.objects.order_by('-timestamp')
    konten = {'title' : 'Lihat Status Laporan', 'respon' : respon}
    return render(request, 'laporan/lihat_laporan.html', konten)

def ubahLaporan(request):
    respon = Laporan.objects.order_by('-timestamp')
    form = FormPilihStatus()
    konten = {'title' : 'Ubah Status Laporan', 'respon' : respon, 'lapor' : form}
    return render(request, 'laporan/ubah_laporan.html', konten)

def lihatUbahLaporan(request):
    if request.user.is_authenticated:
        return redirect('/laporan/ubahLaporan')
    else:
        return redirect('/laporan/lihatLaporan')

def ubahStatusLaporan(request, id):
    ubahStatus = Laporan.objects.get(pk=id)
    respon = Laporan.objects.order_by('-timestamp')
    form = FormPilihStatus(request.POST or None, instance=ubahStatus)
    if form.is_valid():
        ubahStatus = form.save(commit=False)
        ubahStatus.save()
        konten = {'title' : 'Ubah Status Laporan', 'form' : form, 'respon' : respon, 'ubahStatus' : ubahStatus}
        return redirect('/laporan/ubahLaporan')
    else:
        konten = {'title' : 'Ubah Status Laporan', 'form' : form, 'respon' : respon, 'ubahStatus' : ubahStatus}
        return redirect('/laporan/ubahLaporan')

def getData(request):
    return HttpResponse("[]", content_type="text/json-comment-filtered")

def getDataNama(request, nama):
    dataNama = Laporan.objects.filter(nama__contains = nama)
    laporan_list = serializers.serialize('json', dataNama)
    return HttpResponse(laporan_list, content_type="text/json-comment-filtered")

def getDataFull(request):
    data_full = Laporan.objects.all()
    data_full_list = serializers.serialize('json', data_full)
    return HttpResponse(data_full_list, content_type="text/json-comment-filtered")

templates/laporan/lihat_laporan.html
{% extends 'base.html' %}
{% load static %}
{% block navbar-active-status %}active{% endblock navbar-active-status %}

{% block content_block %}
<br>
<div id="lihat_laporan">
    <div class="container">
        <div class="row">
          <div class="col col-lg-8">
            <h1 class="judul">{{ title }}</h1>
          </div>
          
          <div class="col align-self-end">
            <div class="input-group mb-3">
                <input type="text" class="form-control" id="search" placeholder="Nama pelapor" aria-label="Nama pelapor" aria-describedby="basic-addon2">
                <div class="input-group-append">
                  <button id="button-search" class="btn btn-outline-secondary" type="button">Cari</button>
                </div>
               
            </div>
            <div>
              <ul class="list-group" id="result"></ul>
            </div>
          </div>
        </div>
        <br>
        <div>
            <table class="table">
                <thead class="thead-light">
                  <tr>
                    <th class="text-center" style="width: 25%" scope="col">Nama</th>
                    <th class="text-center" style="width: 20%" scope="col">Kategori</th>
                    <th class="text-center" style="width: 20%" scope="col">Status</th>
                    <th style="width: 35%" scope="col"></th>
                  </tr>
                </thead>
                <tbody id="t_body">
                    {% for jawaban in respon %}
                    <tr>
                        <td class="text-center">{{jawaban.nama}}</td>
                        <td class="text-center">Pencurian</td>
                        <td class="text-center">{{jawaban.status}}</td>
                        <td class="text-center"><p>
                            <button id="details_button" class="btn btn-light button-pink" type="button" data-toggle="collapse" data-target="#collapseExample{{ forloop.counter }}" aria-expanded="false" aria-controls="collapseExample">
                              Details
                            </button>
                          </p>
                          <div class="collapse" id="collapseExample{{ forloop.counter }}">
                            <div class="card card-body">
                              <div class="text-justify">
                                {{jawaban.laporan}}
                              </div>
                            </div>
                          </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content_block %}

templates/laporan/ubah_laporan.html
{% extends 'base.html' %}
{% load static %}


{% block content_block %}
<div id="ubah_laporan">
  <div class="container">
      <br>
      <h1 class="judul">{{ title }}</h1>
      <br>
      <div>
          <table class="table" id="table_ubah_laporan">
                <thead class="thead-light">
                  <tr>
                    <th class="text-center" style="width: 22%" scope="col">Nama</th>
                    <th class="text-center" style="width: 20%" scope="col">Kategori</th>
                    <th class="text-center" style="width: 23%" scope="col">Status</th>
                    <th style="width: 35%" scope="col"></th>
                  </tr>
                </thead>
                <tbody>
                    {% for jawaban in respon %}
                    <tr>
                        <td class="text-center">{{jawaban.nama}}</td>
                        <td class="text-center">Pencurian</td>
                        <td>
                          <form method="POST" action="{% url 'laporan:ubahStatusLaporan' id=jawaban.id %}">
                            {% csrf_token %}
                            <select name="status" class="form-control" placeholder="jeje" id="id_status">
                                <option value="1" {{ jawaban.status1 }}>Diproses</option>
                              
                                <option value="2" {{ jawaban.status2 }}>Ditolak</option>
                              
                                <option value="3" {{ jawaban.status3 }}>Selesai</option>
                              
                              </select>
                            <button type="submit" class="btn btn-primary waves-effect waves-light" value="Save">Ubah Status</button>
                          </form>
                        </td>
                        <td class="text-center"><p>
                            <button id="detail_button" class="btn btn-light button-pink" type="button" data-toggle="collapse" data-target="#collapseExample{{ forloop.counter }}" aria-expanded="false" aria-controls="collapseExample">
                              Details
                            </button>
                          </p>
                          <div class="collapse" id="collapseExample{{ forloop.counter }}">
                            <div class="card card-body">
                              <div class="text-justify"> 
                                {{jawaban.laporan}} 
                              </div>
                            </div>
                          </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>    
</div>
{% endblock content_block %}