about/urls.py
from django.urls import path
from . import views

app_name="about"

urlpatterns = [
    path('', views.tentang_kami, name="tentang-kami"),
    path('tambah-pertanyaan/', views.question, name='question'),
    path('json/', views.jsonnya, name='jsonnya'),
]

api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('', views.LaporanView.as_view(), name='LaporanView'),
    path('create/', views.LaporanCreateView.as_view(), name='LaporanView'),   
]

formLaporan/urls.py
from django.urls import path
from formLaporan import views

app_name = 'formLaporan'

urlpatterns = [
    path('', views.buatLaporan, name='buatLaporan'),
]

landingPage/urls.py
from django.urls import path, include
from landingPage import views

app_name = 'landingPage'

urlpatterns = [
    path('', views.index, name="beranda"),
    path('login/', views.login_index, name="login"),
    path('register/', views.register, name="register"),
    path('logout/', views.logout_view, name="logout"),
]

laporan/urls.py
from django.urls import path, include
from laporan import views

app_name = 'laporan'

urlpatterns = [
    path('lihatLaporan/', views.lihatLaporan, name='lihatLaporan'),
    path('ubahLaporan/', views.ubahLaporan, name='ubahLaporan'),
    path('ubahLaporan/<int:id>', views.ubahStatusLaporan, name='ubahStatusLaporan'),
    path('lihatUbahLaporan/', views.lihatUbahLaporan, name='lihatUbahLaporan'),
    path('getData/', views.getData, name='getData'),
    path('getDataFull/', views.getDataFull, name='getDataFull'),
    path('getData/<str:nama>', views.getDataNama, name='getDataNama'),
]

tk1/urls.py
from django.contrib import admin
from django.urls import path, include
# from rest_framework import DefaultRouter
from api.views import LaporanView

# router = DefaultRouter()


urlpatterns = [
    path('admin/', admin.site.urls),
    path('buatLaporan/', include('formLaporan.urls')),
    path('laporan/', include('laporan.urls')),
    path('tentang-kami/', include('about.urls')),
    path('', include("landingPage.urls")),
    path('api/', include("api.urls"))
]

landingPage/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.user.username

landingPage/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ['username', 'email', 'password']

landingPage/views.py
from django.shortcuts import render, redirect
from landingPage.forms import UserForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def index(request):
    return render(request, 'landingPage/index.html')

def login_index(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect("/")
        
    return render(request, 'landingPage/login.html')

def register(request):
    if request.method == "POST":
        user_form = UserCreationForm(request.POST)

        if user_form.is_valid():
            user_form.save()
            return redirect("/")
    else:
        form = UserCreationForm()

        konten = {
            'form' : form,
        }
    return render(request, 'landingPage/register.html', konten)


def logout_view(request):
    logout(request)
    print(request.user)
    return redirect("/")

templates/landingPage/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

<!-- Header -->
{% block title %} Lapor Sis! {% endblock title %}
{% block navbar-active-home %}active{% endblock navbar-active-home %}


<!-- Body -->
{% block content_block %}
    <!-- <div class="container-fluid container-helloWorld d-flex align-items-center justify-content-center">
        <h1 class ="p-2" id="HelloWorld">Coming Soon!</h1>
    </div> -->

    <div class="container container-welcome-message d-flex col-12 ">
        <div class="row col-12 mx-auto my-5 p-4">
            <div class="container m-auto col-md-6">
                <div class="row mx-sm-3">
                <h3 class="">Kamu tidak sendirian! Mari kita hentikan kekerasan bersama-sama, mulai dari kamu!</h3>
                </div>
                <div class="row mt-3 mx-sm-3">
                    <a href="{% url 'formLaporan:buatLaporan' %}" class="btn btn-dark button-pink mr-auto mx-sm-3">Buat Laporan</a>
                    <a href="{% url 'laporan:lihatLaporan' %}" class="btn btn-dark button-pink mx-2 mx-sm-3">Status Laporan</a>
                </div>
            </div>
            <div class="container m-auto col-md-6">
                <div class="row justify-content-center">
                    <div class="col-10">
                        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                <div class="carousel-item active">
                                    <div class="card my-4 my-md-0">
                                        <img src="{% static 'komnas-perempuan.jpg' %}" class="card-img-top mx-auto" style="width: 16em;">
                                        <div class="card-body">
                                            <p class="card-text">Selamat hari Anti kekerasan Terhadap perempuan! Kami berdiri untuk menegakkan keadilan</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="carousel-item">
                                    <div class="card">
                                        <img src="{% static 'three-smiling-orphans.jpg' %}" class="card-img-top mx-auto" alt="..." style="width: 23em;">
                                        <div class="card-body">
                                            <p class="card-text">Anak-anak pun butuh perlindungan! Mari kita dukung dengan mengingatkan terhadap sesama manusia</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="carousel-item">
                                    <div class="card">
                                        <img src="{% static 'lending-hands.png' %}" class="card-img-top" alt="">
                                        <div class="card-body">
                                            <p class="card-text">Keluarga Harmonis Tercipta dari kedamaian! ayo ciptakan Kedamaian</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Previous</span>
                                </a>
                                <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Next</span>
                                </a>
                        </div>                    
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid container-fasilitas d-flex flex-column align-items-center justify-content-center py-3">
        <h1>Kita Bisa Bantu Kamu!</h1>
        <div class="container row py-2 d-flex justify-content-center ">

            <div class="card mx-auto my-3 my-sm-0" style="width: 18rem;">
                <img class="card-img-top mx-auto" src="{% static 'counselling.png' %}" alt="Card image cap" style="width: 16rem;">
                <div class="card-body">
                  <h5 class="card-title text-center">Konseling Trauma</h5>  
                  <p class="card-text text-justify">Lapor-sis menyediakan fasilitas bagi kalian yang menghadapi trauma. Agar, bisa kembali ke kehidupan yang damai</p>
                </div>
            </div>
            
            <div class="card mx-auto my-3 my-sm-0" style="width: 18rem;">
                <img class="card-img-top mx-auto my-2" src="{% static 'law.png' %}" alt="Card image cap" style="width: 10rem;">
                <div class="card-body">
                  <h5 class="card-title text-center">Bantuan Hukum</h5>
                  <p class="card-text text-justify">Bantuan Hukum akan diberikan bagi yang ingin menegakkan keadilan! Lapor-sis menyediakan layanan bagi kalian yang ingin keadilan</p>
                </div>
            </div>
            
            <div class="card mx-auto my-3 my-sm-0" style="width: 18rem;">
                <img class="card-img-top mx-auto" src="{% static 'shield.png' %}" alt="Card image cap" style="width: 10rem;">
                <div class="card-body">
                  <h5 class="card-title text-center">Perlindungan</h5>
                  <p class="card-text text-justify">Kami akan selalu memperjuangkan keadilan serta memberi perlindungan kepada korban    </p>
                </div>
            </div>
        </div> 
    </div>

    <div class="container-fluid container-statistik d-flex flex-column align-items-center py-3 col-12">
        <h1>Berapa Orang Yang Telah Kita Bantu?</h1>
        <div class="container container-statistic-card d-flex flex-wrap justify-content-around">
            
            <div class="card col-sm-5 mx-2 my-4" style="max-width: 540px;">
                <div class="row no-gutters"> 
                    <div class="col-4 my-auto">
                        <h1 id="" class="text-center angka-statistik">5624</h1>
                    </div>   
                    <div class="col-8">
                        <div class="card-body">
                            <h5 class="card-body"  class="text-center">Kasus KDRT</h5>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="card col-sm-5 mx-2 my-4" style="max-width: 540px;">
                <div class="row no-gutters"> 
                    <div class="col-4 my-auto">
                        <h1 id=""  class="text-center angka-statistik ">4562</h1>
                    </div>   
                    <div class="col-8">
                        <div class="card-body">
                            <h5 class="card-body">Kasus Pemerkosaan</h5>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="card col-sm-5 mx-2 my-4" style="max-width: 540px;">
                <div class="row no-gutters"> 
                    <div class="col-4 my-auto">
                        <h1 id=""  class="text-center angka-statistik ">4524</h1>
                    </div>   
                    <div class="col-8">
                        <div class="card-body">
                            <h5 class="card-body">Kasus Perselingkuhan</h5>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="card col-sm-5 mx-2 my-4" style="max-width: 540px;">
                <div class="row no-gutters"> 
                    <div class="col-4 my-auto">
                        <h1 id=""  class="text-center angka-statistik ">1534</h1>
                    </div>   
                    <div class="col-8">
                        <div class="card-body">
                            <h5 class="card-body">Kasus Pelecehan</h5>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="card col-sm-5 mx-2 my-4" style="max-width: 540px;">
                <div class="row no-gutters"> 
                    <div class="col-4 my-auto">
                        <h1 id=""  class="text-center angka-statistik ">9875</h1>
                    </div>   
                    <div class="col-8">
                        <div class="card-body">
                            <h5 class="card-body">Kasus Penelantaran Anak</h5>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="card col-sm-5 mx-2 my-4" style="max-width: 540px;">
                <div class="row no-gutters"> 
                    <div class="col-4 my-auto">
                        <h1 id=""  class="text-center angka-statistik ">1234</h1>
                    </div>   
                    <div class="col-8">
                        <div class="card-body">
                            <h5 class="card-body">Kasus Stalking</h5>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div class="container-fluid container-footer h-30 pt-4 pb-4">
        <h1>Kenali Kami Lebih Baik</h1>
        <a href="{% url 'about:tentang-kami' %}" class="btn btn-dark mt-3">Tentang Kami</a>
    </div>
    
{% endblock content_block %}

templates/landingPage/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

<!-- Header -->
{% block title %} Lapor Sis! {% endblock title %}

<!-- Body -->
{% block content_block %}
    <!-- <div class="container-fluid container-helloWorld d-flex align-items-center justify-content-center">
        <h1 class ="p-2" id="HelloWorld">Coming Soon!</h1>
    </div> -->
    {% if 'next' in request.GET %}
    <script>alert("Silahkan Login terlebih dahulu.\nTerima Kasih :)")</script>
    {%endif%}

    <div class="container-fluid container-login-page d-flex align-items-center col-12 justify-content-center">
        <div class=" container row col-4">
            <h1 id="header-login-page">Login</h1>
            <div class="container container-login border border-secondary rounded-lg">
                <form method="POST"action="{% url 'landingPage:login'%}" class="container m-auto">
                    {% csrf_token %}
                    <label for="username">Username:</label>
                    <input type="text" name="username" id="username" class="form-control">
                    <label for="password">Password:</label>
                    <input type="password" name="password" id="password" class="form-control">
                    <input type="checkbox" onclick="hide()">Show Password</input>
                    <button type="submit" class="btn btn-primary btn-sm align-middle" id="button-login" name="login-button">Login</button>
                </form>
            </div>
        </div>
    </div>
    

   
{% endblock content_block %}

templates/landingPage/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

<!-- Header -->
{% block title %} Lapor Sis! {% endblock title %}
{% block navbar-active-home %}active{% endblock navbar-active-home %}


<!-- Body -->
{% block content_block %}
    <!-- <div class="container-fluid container-helloWorld d-flex align-items-center justify-content-center">
        <h1 class ="p-2" id="HelloWorld">Coming Soon!</h1>
    </div> -->
    <div class="container-fluid container-login-page d-flex align-items-center col-12 justify-content-center">
        <div class=" container row col-4 justify-content-center">
            <h1 id="header-login-page">Register</h1>
            <div class="container container-login border border-secondary rounded-lg">
                    <form action="{% url 'landingPage:register' %}" method="POST">
                        {%csrf_token%}
                        {{form.as_p}}
                        <input type="submit" class="btn btn-primary" value="Daftar" style="float: right;">
                    </form>
                    <br>
                    <br>
                    <br>
                    <p>Are you admin?</p>
                    <a href="{% url 'laporan:ubahLaporan'%}" class="btn btn-danger mb-5"> click me to chage status</a>
            </div>
        </div>
    </div>
    

   
{% endblock content_block %}