about/urls.py
from django.urls import path
from . import views

app_name="about"

urlpatterns = [
    path('', views.tentang_kami, name="tentang-kami"),
    path('tambah-pertanyaan/', views.question, name='question'),
    path('json/', views.jsonnya, name='jsonnya'),
]

api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('', views.LaporanView.as_view(), name='LaporanView'),
    path('create/', views.LaporanCreateView.as_view(), name='LaporanView'),   
]

formLaporan/urls.py
from django.urls import path
from formLaporan import views

app_name = 'formLaporan'

urlpatterns = [
    path('', views.buatLaporan, name='buatLaporan'),
]

landingPage/urls.py
from django.urls import path, include
from landingPage import views

app_name = 'landingPage'

urlpatterns = [
    path('', views.index, name="beranda"),
    path('login/', views.login_index, name="login"),
    path('register/', views.register, name="register"),
    path('logout/', views.logout_view, name="logout"),
]

laporan/urls.py
from django.urls import path, include
from laporan import views

app_name = 'laporan'

urlpatterns = [
    path('lihatLaporan/', views.lihatLaporan, name='lihatLaporan'),
    path('ubahLaporan/', views.ubahLaporan, name='ubahLaporan'),
    path('ubahLaporan/<int:id>', views.ubahStatusLaporan, name='ubahStatusLaporan'),
    path('lihatUbahLaporan/', views.lihatUbahLaporan, name='lihatUbahLaporan'),
    path('getData/', views.getData, name='getData'),
    path('getDataFull/', views.getDataFull, name='getDataFull'),
    path('getData/<str:nama>', views.getDataNama, name='getDataNama'),
]

tk1/urls.py
from django.contrib import admin
from django.urls import path, include
# from rest_framework import DefaultRouter
from api.views import LaporanView

# router = DefaultRouter()


urlpatterns = [
    path('admin/', admin.site.urls),
    path('buatLaporan/', include('formLaporan.urls')),
    path('laporan/', include('laporan.urls')),
    path('tentang-kami/', include('about.urls')),
    path('', include("landingPage.urls")),
    path('api/', include("api.urls"))
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <!-- Meta Tag -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- BootstrapCDN CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href=" {% static 'css/frontpage.css' %}">
    <link rel="stylesheet" href=" {% static 'base.css' %}">
    <link rel="stylesheet" href=" {% static 'css/tentang-kami.css' %}">
    <link rel="stylesheet" href=" {% static 'css/login.css' %}">
    <link rel="stylesheet" href=" {% static 'css/buat_laporan.css' %}">

    <!-- BootstrapCDN JavaScript -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!-- Jquery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    
    <!-- Google Fonts -->

    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker&display=swap" rel="stylesheet"> 
    <!--  font-family: 'Permanent Marker', cursive; -->

    <link href="https://fonts.googleapis.com/css?family=Boogaloo&display=swap" rel="stylesheet"> 
    <!-- font-family: 'Boogaloo', cursive; -->

    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <!-- font-family: 'Montserrat', sans-serif; -->

    <link href="https://fonts.googleapis.com/css?family=Comfortaa&display=swap" rel="stylesheet"> 
    <!-- font-family: 'Comfortaa', cursive; -->

    <link href="https://fonts.googleapis.com/css?family=BenchNine&display=swap" rel="stylesheet"> 
    <!-- font-family: 'BenchNine', sans-serif; -->


    <title>{% block title %}{% endblock title %}</title>
</head>
<body>  
    <nav class="navbar navbar-expand-md container-navbar navbar-dark mx-auto ">
        <a href="/" class="navbar-brand mr-5 ml-2" id="logo">Lapor<span style="color: #b7d2e0">-sis!</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav mr-auto">
                <a href="/" class="nav-link nav-item button-nav {% block navbar-active-home %}{% endblock navbar-active-home %}">Beranda</a>
                {% if user.is_authenticated %}
                    <a href="{% url 'formLaporan:buatLaporan' %}" class="nav-link nav-item button-nav {% block navbar-active-buat %}{% endblock navbar-active-buat %}">Buat Laporan</a>
                {% endif %}
                <a href="{% url 'laporan:lihatUbahLaporan' %}" class="nav-link nav-item button-nav {% block navbar-active-status %}{% endblock navbar-active-status %}">Laporan</a>
                <a href="{% url 'about:tentang-kami' %}" class="nav-link nav-item button-nav {% block navbar-active-about %}{% endblock navbar-active-about %}">Tentang Kami</a>
            </ul>
            <div clas="navbar-nav">
                {% if user.is_authenticated %}
                    <a href="{% url 'landingPage:logout' %}" class="nav-item nav-link button-nav btn btn-danger mt-2 mt-md-0">Logout</a>
                {% else %}
                    <a href="{% url 'landingPage:login' %}" class="nav-item nav-link button-nav btn btn-primary mt-2 mt-md-0">Login</a>                   
                {% endif %} 
            </div>
        </div>
    </nav>
    {% block content_block %}{% endblock content_block %}
    <!-- JavaScript -->
    <script src="{% static 'js/tentang_kami.js' %}"></script>
    <script src="{% static 'js/laporan.js' %}"></script>
    <script src="{% static 'js/buat_laporan.js' %}"></script>
    <script src="{% static 'js/landingPage.js' %}"></script>
</body>
</html>